# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: XWeins Life
email: xie.jinfen@foxmail.com
description: > # this means to ignore newlines until "baseurl:"
  一个分享日常点滴的个人blog
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xweins.com" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: Jeff

copyright:
   name: XWeins
   link: 'https://xweins.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 9
paginate_path: /page:num/

# Tracker
analytics: G-S418WL5M7E

# Comments
disqus: yes
disqus-shortname: xweins-demo

#social
facebook: https://facebook.com/
quora: https://quora.com/
twitter: https://twitter.com/
github: https://github.com/
email: xie.jinfen@foxmail.com

#facebook like box
fb-like-box: yes
fb-app-id: 5494806352195
fb-page-url: https://www.facebook.com/
fb-page-title: XWeins脸书

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

